name: 'Add existing app or test app'

run-name: "Add existing app or test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  AddExistingAppOrTestApp:
    needs: [ ]
    runs-on: [ bc-build ]
    steps:
      - name: Dump Workflow Information
        uses: mazhelez/AL-Go/Actions/DumpWorkflowInfo@fix-incremental-build
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: mazhelez/AL-Go/Actions/WorkflowInitialize@fix-incremental-build
        with:
          shell: powershell
          eventId: "DO0090"

      - name: Read settings
        uses: mazhelez/AL-Go/Actions/ReadSettings@fix-incremental-build
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: mazhelez/AL-Go/Actions/ReadSecrets@fix-incremental-build
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Add existing app
        uses: mazhelez/AL-Go/Actions/AddExistingApp@fix-incremental-build
        with:
          shell: powershell
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: mazhelez/AL-Go/Actions/WorkflowPostProcess@fix-incremental-build
        with:
          shell: powershell
          eventId: "DO0090"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
