name: 'Create a new app'

run-name: "Create a new app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      sampleCode:
        description: Include Sample code?
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateApp:
    needs: [ ]
    runs-on: [ bc-build ]
    steps:
      - name: Dump Workflow Information
        uses: mazhelez/AL-Go/Actions/DumpWorkflowInfo@fix-incremental-build
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: mazhelez/AL-Go/Actions/WorkflowInitialize@fix-incremental-build
        with:
          shell: powershell
          eventId: "DO0092"

      - name: Read settings
        uses: mazhelez/AL-Go/Actions/ReadSettings@fix-incremental-build
        with:
          shell: powershell
          get: type

      - name: Read secrets
        id: ReadSecrets
        uses: mazhelez/AL-Go/Actions/ReadSecrets@fix-incremental-build
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Creating a new app
        uses: mazhelez/AL-Go/Actions/CreateApp@fix-incremental-build
        with:
          shell: powershell
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: ${{ env.type }}
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: mazhelez/AL-Go/Actions/WorkflowPostProcess@fix-incremental-build
        with:
          shell: powershell
          eventId: "DO0092"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
